import { Depth, NdbDocument, ValidKey } from '@normalized-db/core';
import { Predicate } from '../model/predicate';
import { BaseQuery } from './base-query';
import { ListResult } from './list-result/list-result';
import { MapFunc } from './map-reduce/map-func';
import { Mapper } from './map-reduce/mapper';
import { ReducerFunc } from './map-reduce/reduce-func';
import { Reducer } from './map-reduce/reducer';
import { OrderBy } from './model/order-by';
import { QueryConfig } from './model/query-config';
import { Queryable } from './queryable';
export declare class Query<DbItem extends NdbDocument> extends BaseQuery<ListResult<DbItem>> implements Queryable<ListResult<DbItem>> {
    private _offset?;
    private _limit?;
    private _keys?;
    private _filter?;
    private _orderBy?;
    private _parent?;
    private _depth;
    offset(offset: number): this;
    limit(limit: number): this;
    keys(keys: ValidKey[]): this;
    filter(predicate: Predicate<DbItem>, requiresDenormalization?: boolean): this;
    orderBy(orderBy: OrderBy): this;
    nested(key: ValidKey, field: string): this;
    reverse(sourceItem: NdbDocument): this;
    depth(depth: number | Depth): this;
    map<Result>(callback: MapFunc<DbItem, Result>): Mapper<DbItem, Result>;
    reduce<Result>(callback: ReducerFunc<DbItem, Result>, initialValue?: Result): Reducer<DbItem, DbItem, Result>;
    result(noCache?: boolean): Promise<ListResult<DbItem>>;
    count(noCache?: boolean): Promise<number>;
    isEmpty(noCache?: boolean): Promise<boolean>;
    first(noCache?: boolean): Promise<DbItem>;
    firstOrDefault(defaultResult?: DbItem, noCache?: boolean): Promise<DbItem | null>;
    protected getQueryConfig(): QueryConfig;
}
